routes/web.php
<?php

use App\Http\Controllers\Web\AdminController;
use App\Http\Controllers\Web\AuthController;
use App\Http\Controllers\Web\CartController;
use App\Http\Controllers\Web\GalleryInspirasiController;
use App\Http\Controllers\Web\GoogleController;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\OrderController;
use App\Http\Controllers\Web\PembuatanTamanController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Web\Admin\PackageController as AdminPackageController;
use App\Http\Controllers\Web\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Web\Admin\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('', [HomeController::class, 'index'])->name('landingWeb');

Route::get('shop', [ProductController::class, 'index'])->name('shop');
Route::get('shop/{product}', [ProductController::class, 'show'])->name('shop.detail');
Route::post('shop/{product}/cart', [ProductController::class, 'addProductToCart'])->name('shop.detail.cart');
Route::post('shop/{package}/cart/package', [ProductController::class, 'addPackageToCart'])->name('shop.detail.cart.package');

Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'loginStore'])->name('login.store');
Route::post('logout', [AuthController::class, 'logout'])->name('logout');

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle'])->name('google');
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback'])->name('google.callback');


Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('register', [AuthController::class, 'registerStore'])->name('register.store');


Route::get('cart', [CartController::class, 'index'])->name('cart');
Route::delete('carts/{cart}', [CartController::class, 'removeProduct'])->name('cart.remove');
Route::post('carts/{cart}/increment', [CartController::class, 'increment'])->name('cart.increment');
Route::post('carts/{cart}/decrement', [CartController::class, 'decrement'])->name('cart.decrement');

Route::get('orders/store', [OrderController::class, 'create'])->name('orders.store.get');
Route::get('orders', [OrderController::class, 'index'])->name('orders');
Route::get('orders/{order}', [OrderController::class, 'show'])->name('orders.show');
Route::delete('orders/{order}', [OrderController::class, 'destroy'])->name('orders.delete');
Route::post('orders', [OrderController::class, 'store'])->name('orders.store');
Route::get('orders/bukti/{order}', [OrderController::class, 'buktiEdit'])->name('orders.bukti');
Route::post('orders/bukti/{order}', [OrderController::class, 'buktiUpdate'])->name('orders.bukti.store');


Route::get('taman', [PembuatanTamanController::class, 'index'])->name('taman');
Route::get('taman/perawatan', [PembuatanTamanController::class, 'perawatanTaman']) ->name('perawatan');
Route::get('taman/tamanIndoor', [PembuatanTamanController::class, 'tamanIndoor']) ->name('tamanIndoor');
Route::get('taman/tamanOutdoor', [PembuatanTamanController::class, 'tamanOutdoor']) ->name('tamanOutdoor');

Route::get('inspirasi', [GalleryInspirasiController::class, 'index'])->name('inspirasi');

Route::group(['prefix' => 'admin'], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('admin');

    Route::get('orders', [AdminOrderController::class, 'index'])->name('admin.orders');
    Route::get('orders/{order}', [AdminOrderController::class, 'show'])->name('admin.orders.detail');
    Route::put('orders/{order}', [AdminOrderController::class, 'updateStatus'])->name('admin.orders.update');
    Route::get('history', [AdminOrderController::class, 'history'])->name('admin.history');

    Route::get('products', [AdminProductController::class, 'index'])->name('admin.products');
    Route::get('products/store', [AdminProductController::class, 'create'])->name('admin.products.create');
    Route::post('products', [AdminProductController::class, 'store'])->name('admin.products.store');
    Route::get('products/{product}', [AdminProductController::class, 'edit'])->name('admin.products.edit');
    Route::put('products/{product}', [AdminProductController::class, 'update'])->name('admin.products.update');
    Route::delete('products/{product}', [AdminProductController::class, 'destroy'])->name('admin.products.delete');
    
    Route::get('packages', [AdminPackageController::class, 'index'])->name('admin.packages');
    Route::get('packages/store', [AdminPackageController::class, 'create'])->name('admin.packages.create');
    Route::post('packages', [AdminPackageController::class, 'store'])->name('admin.packages.store');
    Route::get('packages/{package}', [AdminPackageController::class, 'edit'])->name('admin.packages.edit');
    Route::put('packages/{package}', [AdminPackageController::class, 'update'])->name('admin.packages.update');
    Route::delete('packages/{package}', [AdminPackageController::class, 'destroy'])->name('admin.packages.delete');
});

app/Models/Package.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;


class Package extends Model
{
    use HasFactory;

    protected $table = 'packages';
    protected $primaryKey = "id";
    protected $keyTypes = "string";
    protected $fillable = [
        'id',
        'nama',
        'harga',
        'image',
        'image_path',
        'deskripsi1',
        'deskripsi2',
        'deskripsi3',
        'deskripsi4',
        'deskripsi5',
    ];
    public $incrementing = false;
    public $timestamps = true;

    protected static function boot()
    {
        parent::boot();


        static::creating(function($model){
            if(empty($model->{$model->getKeyName()})){
                $model->{$model->getKeyName()} = Str::uuid();
            }
            $model->user_id = auth()->user()->id;
        });
    }

    //laravel accesor
    public function getImageAttribute($value)
    {
        return $value ? url($value) : $value;
    }

    //laravel accesor
    public function getImageHoverAttribute($value)
    {
        return $value ? url($value) : $value;
    }

    public function orders()
    {
        return $this->belongsToMany(Order::class, 'order_has_products', 'order_id', 'package_id')->withPivot('qty');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Support\Str;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'google_id',
        'password',
    ];

    protected $primaryKey = "id";
    protected $keyTypes = "string";

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public $incrementing = false;
    public $timestamps = true;

    protected static function boot()
    {
        parent::boot();


        static::creating(function($model){
            if(empty($model->{$model->getKeyName()})){
                $model->{$model->getKeyName()} = Str::uuid();
            }
            $model->user_id = auth()->user()->id;
        });
    }

    public function isAdmin(){
        if($this->role == 'admin'){
            return true;
        }
        return false;
    }
}

resources/views/user/checkout.blade.php
@extends('user.layouts.master')

@section('content')

<!-- Detail Tagihan -->
<div class="md:mx-12 mx-8 md:my-16 my-16">
    <form action="{{ route('orders.store') }}" method="POST">
    @csrf   
    <div class="lg:grid lg:grid-cols-3 gap-8">
          <div class="col-span-2">   
              
              <div class="shadow-xl border  rounded-lg" style="background-color: #F1F5F9;">
              <div class="rounded-t bg-white  px-6 py-6">
                  <h6 class="text-blueGray-700 text-xl font-bold ">
                    My account
                  </h6>
              </div>
                  
                  <form action="#">              
                      <div class="md:flex flex-row md:space-x-4 w-full px-10 mt-8">
                          <div class="mb-3  w-full ">
                              <label class="font-semibold text-gray-600 py-2">Nama Penerima <abbr title="required" class="text-red-600">*</abbr></label>
                              <input required="required" type="text" name="nama_penerima" id="nama_penerima" class="appearance-none block w-full  border rounded-lg h-10 px-4"  />
                              @error('nama_penerima')
                                <div>
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="mb-3 w-full ">
                                <label class="font-semibold text-gray-600 py-2">No. Handphone <abbr title="required" class="text-red-600">*</abbr></label>
                                <input required="required" type="number" name="handphone" id="handphone" class="appearance-none block w-full  border focus-within:border-red-200 rounded-lg h-10 px-4"  />
                                @error('handphone')
                                <div>
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        
                        <div class="w-full mb-4 px-10">
                            <label class="font-semibold text-gray-600 py-2 block"> Provinsi <abbr title="required" class="text-red-600">*</abbr></label>
                            <input type="text" name="provinsi" id="#" class="w-full py-2 px-3">
                            @error('provinsi')
                                <div>
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        
                        <div class="w-full mb-4 mb-4 px-10">
                            <label class="font-semibold text-gray-600 py-2 block"> Kota / Kab<abbr title="required" class="text-red-600">*</abbr></label>
                            <input type="text" name="kota" id="#" class="w-full py-2 px-3/">
                            @error('kota')
                            <div>
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        
                        <div class="flex gap-6 mb-4 px-10">
                            <div class="w-2/3 mb-4">
                                <label class="font-semibold text-gray-600 py-2 block"> Kecamatan<abbr title="required" class="text-red-600">*</abbr></label>
                                <input name="kecamatan" type="text" id="#" class="w-full py-2 px-3"/>
                                @error('kecamatan')
                                    <div>
                                        {{ $message }}
                                    </div>
                                @enderror
                </div>
                
                <div class="w-1/3">
                    <label class="font-semibold text-gray-600 py-2 block"> Kode Pos<abbr title="required" class="text-red-600">*</abbr></label>
                    <input required="required" type="number" name="kodepos" id="kodepos" class="appearance-none block w-full  border focus:border-blue-400 rounded-lg h-10 px-4"  />
                </div>
            </div>
            
            <div class="flex-auto w-full mb-1 py-2 px-10">
                <label class="font-semibold text-gray-600 py-2">Alamat</label>
                <textarea  placeholder="Nama Jalan, nomor rumah Rt/Rw" spellCheck="false" defaultValue=""  required name="alamat"  class=" h-20 appearance-none block w-full bg-grey-lighter text-grey-darker border border-grey-lighter rounded-lg  py-4 px-4" >
                </textarea>
                @error('alamat')
                    <div>
                        {{ $message }}
                    </div>
                @enderror
            </div>
        </form>
    </div> 
</div> 
<!-- End Detail Tagihan -->


<!-- Pesanan anda -->
<div class="col-span-1 mt-10 md:mt-16 lg:mt-0  rounded-md">        
    <div class="shadow-xl border  rounded-lg" style="background-color: #F1F5F9;">
            <div class="rounded-t bg-white  px-6 py-6">
                <h6 class="text-blueGray-700 text-xl font-bold ">
                     Pesanan Anda
                </h6>
            </div>
        <div class="mx-8">
            <div>
                @foreach ($carts as $cart)
                    @if ($cart->product_id == null)
                        <div class="flex justify-between my-2 mt-8">
                            <div> {{ $cart->package->nama }} (paket)</div>
                            <div class="font-semibold"> {{ $cart->package->harga}} * {{ $cart->qty }} pcs</div>   
                        </div>
                    @else
                        <div class="flex justify-between my-2 mt-8">
                            <div> {{ $cart->product->first_name }} {{ $cart->product->last_name }}</div>
                            <div class="font-semibold"> {{ $cart->product->harga}} * {{ $cart->qty }} pcs</div>   
                        </div>
                        
                    @endif
                @endforeach
                
                <div class="mt-5 border-b-2 border-gray-300 pb-5">Sub Total :   <span class="font-semibold">{{ $total }}  </span></div>
            </div>
            
            <div class="py-5 border-b-2 border-gray-300">
                <div class="font-semibold text-xl text-center my-5">Pilih Pengiriman</div>  
                <label class="block my-2"><input type="radio" name="JNE" id="JNE" /><span class="font-semibold ml-1">JNE - REG :</span>  10.000 (1 - 2 hari )</label>
                <label class="block my-2"><input type="radio" name="JNE" id="JNE" /><span class="font-semibold ml-1">JNE - YES :</span>  34.000 (1  hari )</label>
                <label class="block my-2"><input type="radio" name="JNE" id="JNE" /><span class="font-semibold ml-1">TIKI - SDS :</span>  270.000 </label>
            </div>

            <div class="my-5">Total  : <span class="font-semibold"> {{ $total }} </span></div>
        </div>
        
        <div class="text-center mt-10 lg:mt-20 pb-6">
            <button type="submit" class="border border-green-700 text-gray-100 rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:text-white bg-green-700 hover:bg-green-800 focus:outline-none focus:shadow-outline w-1/2" >
                Lanjutkan Checkout
            </button>
            
        </div>
        
    </div>
    
    </div>
</div>

</form>
</div>
<!-- End Pesanan anda -->

@endsection

resources/views/user/gallery-inspirasi.blade.php
@extends('user.layouts.master')


@section('content')
    <div class="text-center text-2xl my-10  font-semibold">
        GALERI
    </div>
    <div class="mx-14 mb-24">
    <div class="h-auto space-y-8 md:h-screen md:grid  md:grid-cols-4 md:grid-rows-4  gap-3 lg:gap-8 ">
        
        <div class="md:row-span-2 lg:row-span-4">
           <img src="/Images/grd1.png" alt="garden" />
           <br />
           <img src="/Images/grd.png" alt="garden" />
        </div>
        <div class="md:col-span-2 lg:col-span-3 relative">
            <img src="/Images/grd2.png" alt="garden" />
            </div>
        <div>
            <img src="/Images/grd3.png" alt="garden" />
            </div>
        <div >
            <img src="/Images/grd4.png" alt="garden" />
            </div>
        <div class="  lg:row-span-2">
            <img src="/Images/grd5.png" alt="garden" />
            </div>
        <div class=" ">
            <img src="/Images/grd6.png" alt="garden" />
            </div>
        <div class=" ">
            <img src="/Images/grd7.png" alt="garden" />
            </div>
     
        
      
        <div class="  md:col-span-2 lg:col-span-3">
        <img src="/Images/grd8.png" alt="garden" />
        </div>
    </div>

    <div class="text-center mt-10 md:mt-60">
        <a
        href="/pages/Taman.html"
        class="mt-3 lg:mt-6 text-sm md:text-lg font-semibold border text-center border-gray-700 text-gray-700 rounded-md px-4 py-2 transition duration-500 ease select-none hover:text-white hover:bg-gray-800 focus:outline-none focus:shadow-outline">
        Lihat Semua  
    </a>
    </div>
    </div>
@endsection

resources/views/user/login.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Naturalisme | Jual Tanaman Hias Jakarta</title>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    @stack('styles')
  </head>

  <body>

    <div>
        <div class="min-w-screen min-h-screen  flex items-center justify-center px-5 py-5">
          <div
            class=" text-gray-500 rounded-3xl shadow-xl w-full overflow-hidden"
            style="max-width: 1000px;"
          >
            <div class="md:flex w-full">
              <div class="hidden md:block w-1/2 py-10 px-10">
                <img src="{{ asset('images/login.png') }}" alt="login" />
              </div>
              <div class="w-full md:w-1/2 py-10 px-5 md:px-10">
                <div class="text-center mb-10">
                  <h1 class="font-bold text-3xl text-gray-900">Login</h1>
                  <p>Sign in to access your account</p>
                </div>
                <form action="{{ route('login.store') }}" method="POST">
                @csrf
                  <div class="flex -mx-3">
                    <div class="w-full px-3 mb-5">
                      <label htmlFor class="text-base font-semibold px-1">
                          Email
                    </label>
                      <div class="flex">
                        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center">
                          <i class="mdi mdi-email-outline text-gray-400 text-lg" >
                              </i>
                        </div>
                        <input
                          type="email"
                          class="w-full -ml-10 pl-10 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-blue-500"
                          placeholder="example@gmail.com"
                          name="email"
                        />
                      </div>
                      @error('email')
                        <div>
                            {{ $message }}
                        </div>
                      @enderror
                    </div>
                  </div>
                  <div class="flex -mx-3">
                    <div class="w-full px-3 mb-7">
                      <label htmlFor class="text-base font-semibold px-1">
                        Password
                      </label>
                      <div class="flex">
                        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center">
                          <i class="mdi mdi-lock-outline text-gray-400 text-lg" >
                         </i>
                        </div>
                        <input
                          type="password"
                          class="w-full -ml-10 pl-10 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-blue-500"
                          placeholder="************"
                          name="password"
                        />
                      </div>
                      @error('password')
                        <div>
                            {{ $message }}
                        </div>
                      @enderror
                    </div>
                  </div>
                  <div class="flex -mx-3">
                    <div class="w-full px-3 mb-5">
                      <button type="submit" class="block w-full max-w-xs mx-auto bg-blue-500 hover:bg-blue-700 focus:bg-blue-700 text-white rounded-lg px-3 py-3 font-semibold">
                        LOGIN
                      </button>
                      <div class="text-center my-5">OR</div>
                      <a href="{{ route('google') }}" class=" flex flex-wrap justify-center text-center w-full max-w-xs mx-auto border hover:bg-gray-100  text-white rounded-lg px-3 py-3 font-semibold">
                          <img src="{{ asset('images/gogle.png') }}" alt="google" class="w-5 items-center">
                      </a>
                    </div>
                  </div>
                  <div class="text-center">
                    Belum punya akun?
                    <a href="{{ route('register') }}">
                     <span class="text-blue-500"> Daftar disini</span>   
                    </a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      
    @stack('scripts')
    
    <script>
      const button = document.querySelector('#butonn');
      const menu = document.querySelector('#menu');

      button.addEventListener('click', () => {
          menu.classList.toggle("hidden")
      })
    </script>
  </body>
</html>

resources/views/user/order.blade.php
@extends('user.layouts.master')


@section('content')
    <div class="mx-5 md:mx-10 mb-20 lg:mb-32">    
        <div class="text-center my-10 text-lg md:text-2xl font-semibold">
           STATUS PEMBAYARAN
        </div>
      <div>
          
          <table class="min-w-full border-collapse block md:table">
              <thead class="block md:table-header-group">
                  <tr class="border border-grey-500 md:border-none block md:table-row absolute -top-full md:top-auto -left-full md:left-auto  md:relative ">
                      <th class="bg-green-600 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">No. Invoice</th>
                      <th class="bg-green-600 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Nama</th>
                      <th class="bg-green-600 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Tanggal</th>
  
                      <th class="bg-green-600 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Actions</th>
                  </tr>
              </thead>
              <tbody class="block md:table-row-group">
                  @foreach ($orders as $order)
                    <tr class="bg-gray-100 border border-grey-500 md:border-none block md:table-row">
                        <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell"><span class="inline-block w-1/3 md:hidden font-bold">No. Invoice</span>  {{ $order->id }}   </td>
                        <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell"><span class="inline-block w-1/3 md:hidden font-bold">Nama</span>{{ $order->nama_penerima }}</td>
                        <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell"><span class="inline-block w-1/3 md:hidden font-bold">Tanggal</span>{{ $order->created_at }}</td>      
                        </td>
                        <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
                            <span class="inline-block w-1/3 md:hidden font-bold">Actions</span>
                            <span class="bg-green-500 text-white font-semibold py-1 px-2 border border-blue-500 rounded">{{ $order->status }}</span>
                            <button class="bg-blue-500 hover:bg-blue-700 text-white font-semibold py-1 px-2 border border-blue-500 rounded"><a href="{{ route('orders.show', ['order'=>$order->id]) }}"> Lihat Invoice</a></button>
                            <a href="{{ route('orders.bukti', ['order'=>$order->id]) }}" class="bg-yellow-500 text-white font-semibold py-1 px-2 border border-yellow-500 rounded">Upload Bukti</a>
                        </td>
                    </tr>
                  @endforeach
                </tbody>
          </table>

          </div>
          </div>
@endsection

resources/views/user/products.blade.php
@extends('user.layouts.master')

@section('content')

    <div class="mx-14">
        <div class="text-xl md:text-2xl lg:text-3xl font-semibold text-center my-10">
          Enjoy Shopping
          </div>
          <div class="flex justify-center border-t border-b border-black p-1 md:p-4">
             <div class="mx-3 text-sm md:text-base md:mx-12">  <a href="{{ route("shop", ['category'=> 'indoor']) }}"> INDOOR</a></div> 
              <div class="mx-3 text-sm md:text-base md:mx-12"> <a href="{{ route("shop", ['category'=> 'outdoor']) }}"> OUTDOOR</a> </div>
              <div class="mx-3 text-sm md:text-base md:mx-12"> <a href="{{ route("shop", ['category'=> 'perlengkapan']) }}">PERLENGKAPAN</a> </div>
              <div class="mx-3 text-sm md:text-base md:mx-12"> <a href="{{ route("shop", ['category'=> 'pupuk']) }}">PUPUK</a> </div>
          </div>
       <div>

    <!-- PRODUCT CARD -->
        <div class="grid grid-cols-2 md:grid-cols-4 mt-10">
            @foreach ($products as $product)
                <div>
                    <div class="bg-white flex">
                        <div class="w-44 md:w-60 p-2 md:p-4 lg:p-3  bg-gray-100 rounded-xl  shadow-xl hover:shadow-3xl  transform duration-500 ">
                            <div class="box">
                                <a href="{{ route('shop.detail', $product->id) }}"> 
                                <img class="w-48 h-40  md:w-60 md:h-44 lg:w-72  lg:h-44  object-cover rounded-t-md" src="{{ $product->image }}" alt="produk" /> 
                                <img class="w-48 h-40  md:w-60 md:h-44 lg:w-72  lg:h-44  object-cover rounded-t-md hover-img " src="{{ $product->image_hover }}" alt="produk" />     
                                </a>
                            </div>
                            <div class="mt-4">
                                <h1 class="text-base font-bold md:text-lg lg:text-xl text-gray-700"><a href="{{ route('shop.detail', $product->id) }}"><span class="text-red-800">{{ $product->first_name }}</span> {{ $product->last_name }} </a></h1>
                                <p class="text-xs md:text-sm italic mt-1 text-gray-700">{{ $product->category->name }}</p>  
                                <div class="mt-3 md:mt-5 mb-2 flex justify-between  pr-2">
                                    <button class="block text-sm md:text-base font-semibold text-gray-700 cursor-auto">{{ $product->harga }}</button> 
                                    <form action="{{ route('shop.detail.cart', $product) }}" method="POST">
                                        @csrf
                                        <button class="text-sm block">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 md:h-6 md:w-6" viewBox="0 0 20 20" fill="currentColor">
                                                <path d="M3 1a1 1 0 000 2h1.22l.305 1.222a.997.997 0 00.01.042l1.358 5.43-.893.892C3.74 11.846 4.632 14 6.414 14H15a1 1 0 000-2H6.414l1-1H14a1 1 0 00.894-.553l3-6A1 1 0 0017 3H6.28l-.31-1.243A1 1 0 005 1H3zM16 16.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM6.5 18a1.5 1.5 0 100-3 1.5 1.5 0 000 3z" />
                                            </svg>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <!-- END PRODUCT CARD -->
        </div>
    </div>
@endsection


@push('styles')
    <style>
			.carousel-open:checked + .carousel-item {
				position: static;
				opacity: 100;
			}
			.carousel-item {
				-webkit-transition: opacity 0.6s ease-out;
				transition: opacity 0.6s ease-out;
			}
			#carousel-1:checked ~ .control-1,
			#carousel-2:checked ~ .control-2,
			#carousel-3:checked ~ .control-3 {
				display: block;
			}
			.carousel-indicators {
				list-style: none;
				margin: 0;
				padding: 0;
				position: absolute;
				bottom: 2%;
				left: 0;
				right: 0;
				text-align: center;
				z-index: 10;
			}
			#carousel-1:checked ~ .control-1 ~ .carousel-indicators li:nth-child(1) .carousel-bullet,
			#carousel-2:checked ~ .control-2 ~ .carousel-indicators li:nth-child(2) .carousel-bullet,
			#carousel-3:checked ~ .control-3 ~ .carousel-indicators li:nth-child(3) .carousel-bullet {
				color: #2b6cb0;  /*Set to match the Tailwind colour you want the active one to be */
			}

      .box {
    position: relative;
    display: inline-block;
    overflow: hidden;
    }

    img.hover-img{
        position: absolute;
        top: 0;
        left: 0;
        opacity: 0;
    }

    .box:hover img {
        opacity: 0;
    }
    .box:hover img.hover-img {
        opacity: 1;
    }
		</style>
@endpush